function [x_backone,P_backone, J_one] =  fixedIntervalSmoother_sspp(x,x_n,P, P_n,phi,Q)
% given a set of estimates generated by the forward Kalman filter, this
% will work backwards to smooth the estimates

P_one = phi *P * phi' + Q;

J_one = P* phi' * inv(P_one);
x_backone = x + J_one * (x_n - phi*x);
P_backone = P + J_one * (P_n - P_one) * J_one';