% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Oct-2021 13:39:17
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
saveVarsMat = load('eg_muRhythmData.mat');

data = saveVarsMat.data; % <1x250000 double> too many elements

clear saveVarsMat;
